### ISSUE TITLE
Verify email link logs user out

### ISSUE THREAD

**Issue by heyiamben** [brettle/meteor-accounts-deluxe#2]
Whenever I load the verify email link it logs the user out without verifying the email address.

**Comment by brettle** [comment]
This should be fixed now. 

Note: if you are logged into an anonymous account and you try to create a new user, `brettle:accounts-add-service` will add the new user to your existing account but will return a `LoginCancelledError` because a new account isn't actually created. Your app, or the accounts UI package it is using, might be interpreting that error in a way that causes you to be logged out or  appear to be logged out. For example, the `useraccounts` suite leaves you in the "signUp" state (which might look like you are logged out but you aren't) until you reload the page. I just came across this today. It is issue brettle/meteor-accounts-add-service#4, if you want to track it.

**Comment by heyiamben** [comment]
Thanks!
